name: Build dist folder

on:
  push:
    branches: ["master"]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm i
      - run: npm run build      
      - name: Declare some variables
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
          echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> "$GITHUB_ENV"
      - run: git add .
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Build ${{ env.sha_short }}"
          branch: build
          create_branch: false
          skip_checkout: true
          push_options: '--force'